### ISSUE TITLE
Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by neumartin** [image-js/mrz-detection#11]
I get this error:

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/mrz-detection/run/getMrz.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by neumartin** [comment]
I fixed with:
npm install -D fs-extra
